version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    groups:
      test-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /ports/typescript
    schedule:
      interval: monthly
    groups:
      typescript-tools:
        patterns: ['*']
