<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>linear_A.Test</RootNamespace>

        <IsPackable>false</IsPackable>

        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="5.0.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\linear-A\linear-A.csproj" />
    </ItemGroup>

</Project>
